export { default as Header } from './Navigation/Header.nav'
export { default as About } from './Sections/About.section'
export { default as Skills } from './Sections/Skills.section'
export { default as Coding } from './Sections/Coding.section'
export { default as Contact } from './Sections/Contact.section'
